### ISSUE TITLE
Problem with distribute package

### ISSUE THREAD

**Issue by francescarpi** [aspineux/pyzmail#20]
On Python Version: 3.5.9
I can't install pyzmail==1.0.3 because I receive the follow error:

 ```
Collecting pyzmail; python_version < "3.6"
  Downloading pyzmail-1.0.3.tar.gz (57 kB)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting lockfile
  Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting distribute
  Downloading distribute-0.7.3.zip (145 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w5vr59s7/distribute/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w5vr59s7/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6v571h0r
         cwd: /tmp/pip-install-w5vr59s7/distribute/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w5vr59s7/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-install-w5vr59s7/distribute/setuptools/extension.py", line 2, in <module>
        import distutils.core
      File "/usr/local/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 83, in create_module
        return importlib.import_module('._distutils', 'setuptools')
      File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: No module named 'setuptools._distutils'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Could anyone help me, please?

Thank you

**Comment by georgemagnuson** [comment]
try installing a forked version (see https://pypi.org/project/pyzmail36/):
pip install pyzmail36
