### ISSUE TITLE
Couldn't install onto Python 3.4

### ISSUE THREAD

**Issue by dukedougal** [aspineux/pyzmail#4]
Hello

I get the following error when trying to install on Python 3.4, any ideas?

Thanks

(venv3.4)pgtrafficcop@core01:/opt/pythonapps/sunnyboy$ pip install pyzmail
Downloading/unpacking pyzmail
Downloading pyzmail-1.0.2.tar.gz (57kB): 57kB downloaded
Running setup.py (path:/home/pgtrafficcop/venv3.4/build/pyzmail/setup.py) egg_info for package pyzmail
Downloading http://pypi.python.org/packages/source/ ... .21.tar.gz
Extracting in /tmp/tmp9z06l8ae
Now working in /tmp/tmp9z06l8ae/distribute-0.6.21
Building a Distribute egg in /home/pgtrafficcop/venv3.4/build/pyzmail
Failed to import the site module
Traceback (most recent call last):
File "/tmp/tmp9z06l8ae/distribute-0.6.21/site.py", line 73, in <module>
__boot()
File "/tmp/tmp9z06l8ae/distribute-0.6.21/site.py", line 2, in __boot
import sys, imp, os, os.path
File "/home/pgtrafficcop/venv3.4/lib/python3.4/imp.py", line 22, in <module>
from importlib import util
File "/home/pgtrafficcop/venv3.4/lib/python3.4/importlib/util.py", line 12, in <module>
from contextlib import contextmanager
ImportError: No module named 'contextlib'
/home/pgtrafficcop/venv3.4/build/pyzmail/distribute-0.6.21-py3.4.egg
Traceback (most recent call last):
File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 143, in use_setuptools
raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/home/pgtrafficcop/venv3.4/build/pyzmail/setup.py", line 11, in <module>
use_setuptools()
File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 145, in use_setuptools
return _do_download(version, download_base, to_dir, download_delay)
File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 125, in _do_download
_build_egg(egg, tarball, to_dir)
File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 116, in _build_egg
raise IOError('Could not build the egg.')
OSError: Could not build the egg.
Complete output from command python setup.py egg_info:
Downloading http://pypi.python.org/packages/source/ ... .21.tar.gz

Extracting in /tmp/tmp9z06l8ae

Now working in /tmp/tmp9z06l8ae/distribute-0.6.21

Building a Distribute egg in /home/pgtrafficcop/venv3.4/build/pyzmail

Failed to import the site module

Traceback (most recent call last):

File "/tmp/tmp9z06l8ae/distribute-0.6.21/site.py", line 73, in <module>

__boot()

File "/tmp/tmp9z06l8ae/distribute-0.6.21/site.py", line 2, in __boot

import sys, imp, os, os.path

File "/home/pgtrafficcop/venv3.4/lib/python3.4/imp.py", line 22, in <module>

from importlib import util

File "/home/pgtrafficcop/venv3.4/lib/python3.4/importlib/util.py", line 12, in <module>

from contextlib import contextmanager

ImportError: No module named 'contextlib'

/home/pgtrafficcop/venv3.4/build/pyzmail/distribute-0.6.21-py3.4.egg

Traceback (most recent call last):

File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 143, in use_setuptools

raise ImportError

ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "<string>", line 17, in <module>

File "/home/pgtrafficcop/venv3.4/build/pyzmail/setup.py", line 11, in <module>

use_setuptools()

File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 145, in use_setuptools

return _do_download(version, download_base, to_dir, download_delay)

File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 125, in _do_download

_build_egg(egg, tarball, to_dir)

File "/home/pgtrafficcop/venv3.4/build/pyzmail/distribute_setup.py", line 116, in _build_egg

raise IOError('Could not build the egg.')

OSError: Could not build the egg.

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/pgtrafficcop/venv3.4/build/pyzmail
Storing debug log for failure in /home/pgtrafficcop/.pip/pip.log
(venv3.4)pgtrafficcop@core01:/opt/pythonapps/sunnyboy$

**Comment by lseongjoo** [comment]
Same problem during install on python 3.5 (Anaconda)

$ pip install pyzmail

AttributeError: _DistInfoDistribution__dep_map

```
During handling of the above exception, another exception occurred:
```

...

ImportError: No module named '_markerlib'

## 

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7d/5cfd89tj4s7gtscfh0lsp9qc0000gn/T/pip-build-3742glcu/distribute/

**Comment by xjr7670** [comment]
May I ask whether you have solved this problem?

## Because it confuse me too right now.

C:\Users\Jiarong>pip3 install pyzmail
Collecting pyzmail
  Using cached pyzmail-1.0.3.tar.gz
Collecting distribute (from pyzmail)
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\distribute.egg-info
    writing pip-egg-info\distribute.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\distribute.egg-info\dependency_link
s.txt
    writing requirements to pip-egg-info\distribute.egg-info\requires.txt
    writing top-level names to pip-egg-info\distribute.egg-info\top_level.txt
    Traceback (most recent call last):
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2680, in _dep_map
        return self.__dep_map
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2525, in __getattr__
        raise AttributeError(attr)
    AttributeError: _DistInfoDistribution__dep_map

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\se
```

tup.py", line 58, in <module>
        setuptools.setup(**setup_params)
      File "D:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "D:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\se
tuptools\command\egg_info.py", line 177, in run
        writer = ep.load(installer=installer)
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2241, in load
        if require: self.require(env, installer)
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2254, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer)))
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2471, in requires
        dm = self._dep_map
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2682, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "C:\Users\Jiarong\AppData\Local\Temp\pip-build-o4jjt_ku\distribute\pk
g_resources.py", line 2699, in _compute_dependencies
        from _markerlib import compile as compile_marker
    ImportError: No module named '_markerlib'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Jiarong\
AppData\Local\Temp\pip-build-o4jjt_ku\distribute\

**Comment by gryken2014** [comment]
I've got the same issue.
-> python 3.4.4 (64bits) ;
-> windows 7 64bits

Command : 
 pip3.4 install pyzmail

Same traceback and error messages than @xjr7670 .

**Comment by kgriffen** [comment]
Same here.

**Comment by AbsoluteVirtue** [comment]
easy_install pyzmail worked for me, but my dev environment still doesn't recognize "import pyzmail". help :(
